spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources

  thymeleaf:
    cache: false
    check-template-location: true
  #Content-Type
    servlet:
      content-type: text/html
    #excluded-view-names:
    mode: HTML
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

#  messages:
#    basename: i18n.messages
#    fallback-to-system-locale: false

    #spring.messages.encoding=UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      resolve-lazily: true
      max-request-size: 10MB
      location:
  application:
    name: CommonSenseCaptcha
#Thymeleaf End


#Server Configuration
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
  servlet:
    session:
      timeout: 30m

#Log Configuration
logging:
  level:
    org:
      springframework: WARN